ProductsApp/Models/ErrorViewModel.cs
using System;

namespace ProductsApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductsApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProductsApp.Models;

namespace ProductsApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductsApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductsApp.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Edit()
        {
            return View();
        }
    }
}

ProductsApp/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductsApp.Controllers
{
    public class ProdutosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Edit()
        {
            return View();
        }
    }
}

ProductsApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProductsApp/Views/Products/Add.cshtml
@{
    ViewData["Title"] = "Cadastrar Produto";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h1>Cadastrar Produto</h1>
            </div>
            <div class="card-body">
                <form action="">
                    <div class="row">
                        <div class="col-2">
                            <label for="Id">Código</label>
                        </div>
                        <div class="col-10">
                            <input type="text" id="Id" name="Id" disabled class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Nome">Nome</label>
                        </div>
                        <div class="col-10">
                            <input type="text" id="Nome" name="Nome" class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Estoque">Estoque</label>
                        </div>
                        <div class="col-10">
                            <input type="number" id="Estoque" name="Estoque" class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Preco">Preço</label>
                        </div>
                        <div class="col-10">
                            <input type="number" step="0.01" id="Preco" name="Preco" class="form-control">
                        </div>
                    </div>
                </form>
            </div>

            <div class="card-footer">
                <button class="btn btn-outline-success" id="btnSalvar">Salvar</button>
                <button class="btn btn-outline-danger" id="btnCancelar">Cancelar</button>
            </div>

        </div>
    </div>
</div>


@section Scripts {

<script>

    $(document).on('click', '#btnCancelar', function(e) {
        window.location.href = "/products"
    });

    $(document).on('click', '#btnSalvar', function (e) {
        e.preventDefault();

        var data = {
            nome: $("#Nome").val(),
            estoque: $("#Estoque").val(),
            preco: $("#Preco").val()
        }

        if ((data.nome == "") || (data.estoque == "") || (data.preco == "")) {
            alert("Favor preencher todos os campos.");
        } else {
            axios.post('https://localhost:60001/produto', data)
                .then(function (response) {

                    alert('Cadastro efetuado com sucesso')
                    window.location.href = "/products"

                })
                .catch(function (error) {
                    alert('Verifique se a api esta funcionando')
                    console.log(error);
                })
        }

    });

</script>

}

ProductsApp/Views/Products/Index.cshtml
@{
    ViewData["Title"] = "Lista de Produtos";
}

<div class="card">
    <div class="card-header">
        <h3>Lista de Produtos</h3>
    </div>
    <div class="card-body">
        <a href="products/Add"><button type="button" class="btn btn-outline-primary">+ Adicionar</button></a>
    </div>
</div>
<br>

<table width="100%" id="lista">
    <thead>
        <tr>
            <th bgcolor="#33adff">Codigo</th>
            <th bgcolor="#33adff">Nome</th>
            <th bgcolor="#33adff">Estoque</th>
            <th bgcolor="#33adff">Preço</th>
            <th bgcolor="#33adff" colspan="2"></th>
        </tr>
    </thead>
    <tbody>


    </tbody>
</table>

@section Scripts {

<script>

    $(document).ready(function () {
        LoadProdutos();
    })

    function LoadProdutos() {
        $("#lista > tbody").empty();

        axios.get('https://localhost:60001/produto/getprodutos')
            .then(function (response) {
                response.data.forEach(a => {
                    console.log(a);
                    $("#lista > tbody").append(`<tr><td>${a.id}</td><td>${a.nome}</td><td>${a.estoque}</td><td>${a.preco}</td><td><a class="btn btn-outline-primary" href="products/edit?id=${a.id}">Editar</a></td><td><a class="btn btn-outline-danger" href="javascript:Excluir(${a.id})">Excluir</a></td></tr>`)
                })
            })
            .catch(function (error) {
                alert('Verifique se a api esta funcionando')
                console.log(error);
            })
    }

    function Excluir(id) {
        let result = confirm("Deseja Excluir o Item?");

        if (result) {
            axios.delete('https://localhost:60001/produto/' + id)
                .then(function (response) {
                    LoadProdutos();
                })
                .catch(function (error) {
                    // handle error
                    alert('Verifique se a api esta funcionando')
                    console.log(error);
                })
        }
    }
</script>

}

ProductsApp/Views/Products/edit.cshtml
@{
    ViewData["Title"] = "Alterar Produto";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h1>Alterar Produto</h1>
            </div>
            <div class="card-body">
                <form action="">
                    <div class="row">
                        <div class="col-2">
                            <label for="Id">Código</label>
                        </div>
                        <div class="col-10">
                            <input type="text" id="Id" name="Id" disabled class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Nome">Nome</label>
                        </div>
                        <div class="col-10">
                            <input type="string" id="Nome" name="Nome" class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Estoque">Estoque</label>
                        </div>
                        <div class="col-10">
                            <input type="number" id="Estoque" name="Estoque" class="form-control">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <label for="Preco">Preço</label>
                        </div>
                        <div class="col-10">
                            <input type="number" step="0.01" id="Preco" name="Preco" class="form-control">
                        </div>
                    </div>

                </form>
            </div>

            <div class="card-footer">
                <button class="btn btn-outline-success" id="btnSalvar">Salvar</button>
                <button class="btn btn-outline-danger" id="btnCancelar">Cancelar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {

<script>

    const idProduto = '@Context.Request.Query["id"]';

    $(document).ready(function () {

        loadProduto();

    });

    $(document).on('click', '#btnCancelar', function (e) {
        window.location.href = "/products"
    });

    $(document).on('click', '#btnSalvar', function (e) {
        e.preventDefault();

        var data = {
            nome: $("#Nome").val(),
            estoque: $("#Estoque").val(),
            preco: $("#Preco").val()
        }

        if ((data.nome == "") || (data.estoque == "") || (data.preco == "")) {
            alert("Favor preencher todos os campos.");
        } else {
            axios.put('https://localhost:60001/produto/' + idProduto, data)
                    .then(function (response) {
                        alert('Alteração efetuada com sucesso')
                        window.location.href = "/products"
                    })
                    .catch(function (error) {
                        alert('Verifique se a api esta funcionando')
                        console.log(error);
                    })

        }
    });


    function loadProduto() {

        axios.get('https://localhost:60001/produto/GetProduto/' + idProduto)
            .then(function (response) {
                $("#Id").val(response.data.id);
                $("#Nome").val(response.data.nome);
                $("#Estoque").val(response.data.estoque);
                $("#Preco").val(response.data.preco);
            })
            .catch(function (error) {
                alert('Verifique se a api esta funcionando')
                console.log(error);
            })
    }

</script>

}

ProductsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">ProductsApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Produtos</a>
                        </li>                        
                        <!-- <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProductsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>